package hecho

import (
	"strings"

	"github.com/labstack/echo/v4"
	"github.com/labstack/echo/v4/middleware"
	"go.uber.org/zap"

	"github.com/stellwerk-labs/golib/herrors"
	"github.com/stellwerk-labs/golib/hlogger"
)

const (
	PlatformOrchestratorUserAgentHeader = "Platform-Orchestrator-User-Agent"
)

type LoggerConfig struct {
	Logger        *zap.Logger
	SilencedPaths []string
}

func GetRequestLoggerConfig(config *LoggerConfig) middleware.RequestLoggerConfig {
	silencedPathsMap := make(map[string]bool, len(config.SilencedPaths))
	for _, ignoredPath := range config.SilencedPaths {
		silencedPathsMap[ignoredPath] = true
	}
	logger := config.Logger
	return middleware.RequestLoggerConfig{
		LogURI:          true,
		LogStatus:       true,
		LogMethod:       true,
		LogError:        true,
		LogLatency:      true,
		LogResponseSize: true,
		LogProtocol:     true,
		LogUserAgent:    true,
		LogRequestID:    true,
		// Initialise the platform-orchestrator IDs on each request so that we can adjust them later and then log them
		// at the end.
		BeforeNextFunc: func(c echo.Context) {
			_, ctx := hlogger.EnsurePlatformOrchestratorIdsOnCtx(c.Request().Context())
			c.SetRequest(c.Request().WithContext(ctx))
		},
		// HandleError is called now because we need to convert and commit the error before logging the status code and
		// response size.
		HandleError: true,
		// LogHeaders sets which headers to collect and expose to LogValuesFunc
		LogHeaders: []string{PlatformOrchestratorUserAgentHeader},
		LogValuesFunc: func(c echo.Context, v middleware.RequestLoggerValues) error {
			// See https://docs.datadoghq.com/logs/log_configuration/attributes_naming_convention/#http-requests for the naming
			httpDetails := map[string]interface{}{
				"url":           v.URI,
				"status_code":   v.Status,
				"method":        v.Method,
				"useragent":     v.UserAgent,
				"version":       v.Protocol,
				"response_size": v.ResponseSize,
			}

			// Various sdk, cli, and other clients provide a platform-orchestrator user agent. We can log this if it's present!
			if values, _ := v.Headers[PlatformOrchestratorUserAgentHeader]; len(values) > 0 && len(values[0]) > 0 {
				httpDetails["platform_orchestrator_useragent"] = strings.Join(values, "; ")
			}

			// This will be collected by OperationIdCollectorMiddleware if configured
			if op, ok := GetOperationId(c.Request().Context()); ok {
				httpDetails["op"] = op
			}

			// If there's a request id generated for this request yet, then log it, otherwise ignore for backwards
			// compatibility. The request id is usually generated by echo/v4/middleware.RequestIDWithConfig
			if rid := v.RequestID; rid != "" {
				httpDetails["request_id"] = rid
			}

			logger := logger

			// add platform-orchestrator id's to the logger that we'll call below
			if ids, ok := hlogger.GetPlatformOrchestratorIdsFromCtx(c.Request().Context()); ok {
				logger = logger.With(ids.AsLogField())
			}

			ctxArgs := []interface{}{"http", httpDetails, "duration", v.Latency.Nanoseconds()}
			if v.Error != nil {
				errDetails := map[string]interface{}{}

				if herr, ok := v.Error.(*herrors.PlatformOrchestratorError); ok {
					httpDetails["status_code"] = herr.StatusCode
					for key, value := range herr.Details {
						errDetails[key] = value
					}
					errDetails["err"] = herr.Error()
				} else {
					errDetails["err"] = v.Error.Error()
				}
				ctxArgs = append(ctxArgs, "err", errDetails)
			}

			args := hlogger.LogDetailsFromCtx(c.Request().Context(), ctxArgs...)
			switch {
			case silencedPathsMap[v.URI]:
				logger.Sugar().Debugw("handled silenced path", args...)
			case v.Status >= 500:
				logger.Sugar().Errorw("handled", args...)
			case v.Status >= 400:
				logger.Sugar().Warnw("handled", args...)
			default:
				logger.Sugar().Infow("handled", args...)
			}
			return nil
		},
	}
}
