package hecho

import (
	"context"
	"time"

	"github.com/labstack/echo/v4"
	"github.com/labstack/echo/v4/middleware"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
)

// BuildContextTimeoutMiddleware converts a ContextTimeoutConfig into a handler that can be used in the strict-echo
// code generated by the oapi-codegen.
//
// Note that the default error handler provided by the config can convert the deadline exceeded into a server
// unavailable 503 which may or may not be what you expect.
//
// Note that this works better than the normal ContextTimeoutWithConfig when used with the strict echo server because
// it can be evaluated after the OperationIdCollectorMiddleware and thus change skipping configuration based on the
// operation id.
func BuildContextTimeoutMiddleware(config middleware.ContextTimeoutConfig) strictecho.StrictEchoMiddlewareFunc {
	return func(f strictecho.StrictEchoHandlerFunc, operationID string) strictecho.StrictEchoHandlerFunc {
		return func(ctx echo.Context, request interface{}) (response interface{}, err error) {
			if config.Skipper != nil && config.Skipper(ctx) {
				return f(ctx, request)
			}

			timeoutContext, cancel := context.WithTimeout(ctx.Request().Context(), config.Timeout)
			defer cancel()

			ctx.SetRequest(ctx.Request().WithContext(timeoutContext))

			resp, err := f(ctx, request)
			if err != nil && config.ErrorHandler != nil {
				err = config.ErrorHandler(err, ctx)
			}
			return resp, err
		}
	}
}

// BuildContextTimeoutMiddlewareWithDuration is a shortcut for minimal configuration
func BuildContextTimeoutMiddlewareWithDuration(timeout time.Duration) strictecho.StrictEchoMiddlewareFunc {
	return BuildContextTimeoutMiddleware(middleware.ContextTimeoutConfig{Timeout: timeout})
}
